-- Inserir Arrancador de Bateria c/ Compressor de Ar Portátil Q18B
INSERT INTO products (user_id, nome, categoria, resumo, cards) VALUES (
  'ab822b2c-cfc1-4c7f-adfd-6cf11e2bcf58',
  'Arrancador de Bateria c/ Compressor de Ar Portátil Q18B',
  'Automotivo',
  'O Arrancador de Bateria com Compressor de Ar Portátil Q18B é um equipamento 4 em 1 desenvolvido para oferecer mais segurança e praticidade em situações de emergência e no dia a dia. Além de dar partida em veículos 12V, ele também funciona como compressor de ar portátil, power bank para carregar dispositivos eletrônicos e lanterna LED com modo SOS.

Compacto e fácil de transportar, cabe no porta-luvas e acompanha todos os acessórios necessários para uso imediato, incluindo grampos inteligentes, mangueira de alta pressão, adaptadores, cabo USB-C e bolsa de armazenamento. É uma solução completa para viagens, estrada e uso diário.',
  '[
    {"cat":"Problemas que resolve","items":["Resolve bateria descarregada em carros e motos 12V.","Evita ficar parado por causa de pneu murcho.","Permite calibrar pneus em qualquer lugar.","Carrega celular e outros eletrônicos em emergências.","Oferece iluminação em locais escuros ou situações de emergência.","Elimina a necessidade de carregar vários equipamentos separados."]},
    {"cat":"Benefícios","items":["Mais segurança durante viagens e imprevistos.","Economia de tempo ao resolver problemas sem precisar de ajuda imediata.","Quatro funções reunidas em um único equipamento.","Fácil transporte por ser compacto.","Ajuste preciso da pressão dos pneus.","Desligamento automático ao atingir a pressão programada.","Carregamento rápido para dispositivos eletrônicos.","Proteções eletrônicas aumentam a segurança durante o uso."]},
    {"cat":"Características importantes","items":["Arrancador para veículos 12V.","Bateria recarregável de 8000mAh.","Compressor com pressão máxima de 150 PSI.","Precisão de 0,1 BAR.","Display digital para ajuste da pressão.","Desligamento automático do compressor.","Power Bank com duas portas USB (5V/3A e 5V/2A).","Lanterna LED com luz contínua e modo SOS.","Entrada USB Type-C.","Recarga completa em aproximadamente 4 a 5 horas.","Proteção contra inversão de polaridade, curto-circuito, sobrecarga, superaquecimento e sobrecorrente.","Dimensões compactas (200 x 108 x 60 mm)."]},
    {"cat":"Diferenciais","items":["Equipamento 4 em 1.","Compressor inteligente que para automaticamente.","Display digital facilita a calibração.","Grampos inteligentes com múltiplas proteções.","Cabe no porta-luvas.","Acompanha diversos acessórios prontos para uso."]},
    {"cat":"Possíveis testes","items":["Dar partida em um veículo com bateria fraca.","Calibrar um pneu mostrando o desligamento automático.","Encher uma bola utilizando os adaptadores.","Carregar um celular pela porta USB.","Demonstrar os modos da lanterna LED.","Mostrar todo o conteúdo da bolsa de armazenamento."]},
    {"cat":"Possíveis momentos WOW","items":["O carro liga usando apenas o arrancador.","O compressor para sozinho exatamente na pressão programada.","Mostrar que o aparelho cabe no porta-luvas.","Demonstrar as quatro funções funcionando no mesmo vídeo.","Carregar um celular enquanto o equipamento ainda possui bateria.","Mostrar todos os acessórios saindo da bolsa."]},
    {"cat":"Público ideal","items":["Motoristas de carros.","Motociclistas.","Motoristas de aplicativo.","Caminhoneiros.","Pessoas que viajam com frequência.","Quem gosta de estar preparado para emergências.","Famílias que utilizam veículo diariamente."]},
    {"cat":"Objeções do comprador","items":["\"Será que realmente consegue ligar o carro?\"","\"É difícil de usar?\"","\"O compressor calibra corretamente?\"","\"Vale a pena comprar um equipamento 4 em 1?\"","\"Ocupa muito espaço no carro?\""]},
    {"cat":"Respostas às objeções","items":["Foi desenvolvido para auxiliar na partida de veículos 12V conforme as condições informadas no anúncio.","O uso é simplificado, com grampos identificados e display digital.","O compressor possui ajuste de pressão e desligamento automático ao atingir o valor programado.","Além de dar partida, também funciona como compressor, power bank e lanterna LED.","O equipamento possui dimensões compactas e foi projetado para caber no porta-luvas."]},
    {"cat":"Curiosidades","items":["O compressor possui precisão de ajuste de 0,1 BAR.","A lanterna possui modo SOS para emergências.","Os grampos contam com proteção contra inversão de polaridade, evitando ligações incorretas.","O equipamento suporta temperaturas de operação entre -20°C e 60°C.","A recarga é feita por USB Type-C.","Acompanha adaptadores para pneus de carro, moto, bicicleta, bolas e infláveis."]}
  ]'::jsonb
);
