-- Seed: Banco padrão de ganchos por categoria (genéricos — qualquer produto)
-- Run in Supabase SQL Editor (usa auth.uid() do usuário logado)

INSERT INTO ganchos (user_id, categoria, texto)
SELECT (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), v.categoria, v.texto
FROM (VALUES
('Emergência', 'Imagina precisar disso exatamente no momento em que você mais precisa.'),
('Emergência', 'Você só lembra desse produto quando já é tarde demais.'),
('Emergência', 'E se você precisar disso hoje?'),
('Emergência', 'Já pensou ficar na mão num momento crítico?'),
('Emergência', 'A pior hora para descobrir que precisava disso é agora.'),
('Emergência', 'Ninguém sai de casa pensando que vai precisar disso.'),
('Emergência', 'Cinco minutos podem mudar completamente o seu dia.'),
('Emergência', 'Tem uma situação que todo mundo morre de medo de enfrentar.'),
('Emergência', 'Isso pode acontecer com qualquer pessoa.'),
('Emergência', 'Eu espero que você nunca precise usar isso.'),
('Essencial', 'Se você quer resolver de vez, esse vídeo é obrigatório.'),
('Essencial', 'Todo mundo deveria ter um desses em casa.'),
('Essencial', 'Você gasta com tanta coisa e esquece do essencial.'),
('Essencial', 'Existe um item que deveria estar em todo kit de ferramentas.'),
('Essencial', 'Se você valoriza praticidade, precisa conhecer isso.'),
('Essencial', 'Tem uma coisa que eu nunca fico sem.'),
('Essencial', 'Quem trabalha todos os dias vai entender esse vídeo.'),
('Essencial', 'Eu não deixaria de ter isso.'),
('Essencial', 'O item mais útil que você pode ter talvez seja esse.'),
('Essencial', 'Se você resolve as coisas sozinho, presta atenção.'),
('Viagens', 'Vai viajar nas férias?'),
('Viagens', 'Antes de viajar, assiste esse vídeo.'),
('Viagens', 'O maior erro de quem viaja.'),
('Viagens', 'Você prepara tudo... mas esquece disso.'),
('Viagens', 'Se sua família viaja, veja isso.'),
('Viagens', 'Tem um item que pode salvar sua viagem.'),
('Viagens', 'Eu não viajaria sem isso.'),
('Viagens', 'Quem faz viagem longa precisa conhecer.'),
('Viagens', 'Essa dica vale ouro para quem gosta de viajar.'),
('Viagens', 'Leva menos espaço que uma garrafa de água.'),
('Economia', 'Quer economizar centenas de reais?'),
('Economia', 'Isso pode evitar uma dor de cabeça.'),
('Economia', 'Um produto pode evitar um prejuízo enorme.'),
('Economia', 'O barato pode sair caro... menos nesse caso.'),
('Economia', 'Você gasta com proteção, mas esquece disso.'),
('Economia', 'Tem gente pagando por um problema que resolveria em minutos.'),
('Economia', 'Esse produto pode se pagar na primeira emergência.'),
('Economia', 'Quanto custa ficar na mão esperando ajuda?'),
('Economia', 'Muito mais barato do que pagar por um serviço de emergência.'),
('Economia', 'Uma compra pode evitar muita dor de cabeça.'),
('Identificação', 'Você já ficou na mão exatamente quando precisava?'),
('Identificação', 'Quem nunca passou por isso?'),
('Identificação', 'Se você já precisou pedir ajuda para não passar aperto...'),
('Identificação', 'Você conhece alguém que precisa disso?'),
('Identificação', 'Quem nunca esqueceu de algo importante?'),
('Identificação', 'Já ficou sem bateria no celular durante uma viagem?'),
('Identificação', 'Você já passou por algum perrengue?'),
('Identificação', 'Qual foi o maior sufoco que você já passou?'),
('Identificação', 'Aposto que isso já aconteceu com você.'),
('Identificação', 'Se ainda não aconteceu... um dia pode acontecer.'),
('Curiosidade', 'Descobri um equipamento que faz muito mais do que parece.'),
('Curiosidade', 'Eu achei que isso servia para uma coisa só.'),
('Curiosidade', 'Tem uma função escondida que ninguém comenta.'),
('Curiosidade', 'O tamanho desse equipamento engana.'),
('Curiosidade', 'Não parece, mas isso pode salvar o seu dia.'),
('Curiosidade', 'É compacto e resolve um problemão.'),
('Curiosidade', 'Eu fiquei surpreso com tudo que ele faz.'),
('Curiosidade', 'O recurso mais útil nem é o principal.'),
('Curiosidade', 'Parece simples... até você precisar.'),
('Curiosidade', 'Esse pode ser o item mais inteligente que você vai ter.'),
('Família', 'Se você se preocupa com sua família...'),
('Família', 'Quem tem filhos deveria pensar nisso.'),
('Família', 'A última coisa que você quer é passar aperto com a família.'),
('Família', 'Segurança também é estar preparado.'),
('Família', 'Sua família vai agradecer quando isso for útil.'),
('Família', 'Quem viaja com crianças entende.'),
('Família', 'Eu prefiro prevenir do que remediar.'),
('Família', 'Um pai de família deveria conhecer isso.'),
('Família', 'É um daqueles produtos que traz tranquilidade.'),
('Família', 'Eu compraria só pela paz de espírito.'),
('Dia a dia', 'Quem trabalha pesado, presta atenção.'),
('Dia a dia', 'Se o seu dia a dia depende disso, continua assistindo.'),
('Dia a dia', 'Você depende de ferramentas para trabalhar?'),
('Dia a dia', 'Uma falha simples pode acabar com o seu dia.'),
('Dia a dia', 'Se a sua ferramenta falhar, você faz o quê?'),
('Dia a dia', 'Esse produto deveria estar em toda casa.'),
('Dia a dia', 'Para quem vive no corre.'),
('Dia a dia', 'Seu trabalho depende de você estar preparado?'),
('Dia a dia', 'Você já ficou na mão no pior momento?'),
('Dia a dia', 'Esse pode ser seu melhor companheiro no dia a dia.'),
('Medo', 'O problema nunca avisa quando vai acontecer.'),
('Medo', 'O imprevisto sempre escolhe a pior hora.'),
('Medo', 'Você nunca acha que vai acontecer com você.'),
('Medo', 'O dia que isso acontecer, você vai lembrar desse vídeo.'),
('Medo', 'Não espere precisar para comprar.'),
('Medo', 'A prevenção sempre custa menos.'),
('Medo', 'Tem coisa que a gente compra esperando nunca usar.'),
('Medo', 'Se um dia precisar, está aí.'),
('Medo', 'Mas se precisar...'),
('Medo', 'Você vai agradecer por ter comprado.'),
('Desafio/Teste', 'Será que isso realmente funciona do jeito que promete?'),
('Desafio/Teste', 'Vamos descobrir se isso funciona de verdade.'),
('Desafio/Teste', 'Eu resolvi testar esse equipamento.'),
('Desafio/Teste', 'Promete ser útil de verdade... será?'),
('Desafio/Teste', 'Vale mesmo o preço que cobram?'),
('Desafio/Teste', 'Bora colocar à prova.'),
('Desafio/Teste', 'Hoje eu vou tentar fazer ele falhar.'),
('Desafio/Teste', 'Será que ele entrega o que promete?'),
('Desafio/Teste', 'O Cara Testou... e olha o resultado.'),
('Desafio/Teste', 'Vamos ver se isso merece ser aprovado.')
) AS v(categoria, texto)
ON CONFLICT DO NOTHING;