-- Seed: Categoria "Leal" (ganchos de preço/oferta — genéricos)
-- Run in Supabase SQL Editor

INSERT INTO ganchos (user_id, categoria, texto)
SELECT (SELECT id FROM auth.users ORDER BY created_at LIMIT 1), 'Leal', v.texto
FROM (VALUES
('Minha esposa esta comprando todas as …. Dessa loja só Porque esta menos de ….'),
('Agora eu descobrir o segredo dele para…..'),
('Essa daqui tá valendo a pena'),
('Menos de x está dado, tem loja vendendo por x.'),
('Duas x por menos de Y'),
('Essa daqui é pra x exigente'),
('-gastou todo dinheiro que tinha na x , gastei não paguei menos de x'),
('É só abrir assim fazer isso e já dar pra usar'),
('Esse é o x que deixa qualquer x feliz'),
('Agora ficou fácil fazer x, por menos de Y.'),
('Por menos de x eu vou fazer Y.'),
('Ninguém acredita quando eu digo que…'),
('Ninguém acredita quando eu digo que gastei x'),
('Só paga caro em x quem quiser'),
('Então esse é seu segredo'),
('Não preciso de x (funcionário) mais'),
('Esse aqui não precisa x não, não é aquele Y não.'),
('Minha x vai surtar com essa Y'),
('Olha o que eu achei o TikTok pela metade do preço'),
('X versus Y (maquiagem da mulher versus maquiagem do homem)'),
('A hora de x é agora por menos de x'),
('Voltou para o estoque por menos de x'),
('Esse é o que x que eu uso para'),
('Esse aqui me x'),
('Essa é a diferença entre x e Y'),
('O cara que inventou isso aqui é um gênio'),
('O único problema é o preço tá muito barato'),
('Esse aqui é x e achei por menos de Y'),
('Eu só acreditei porque ela comprou com meu cartão'),
('Ninguém vai acreditar que você pagou menos de x'),
('Esse aqui tá tão barato que eu comprei logo x'),
('Economizei quase x comprando aqui'),
('Esse aqui é o x que eu falei com vocês menos de y'),
('Baixou o preço do x mais viralizado'),
('Faz isso também, esse aqui é o x que faz Y'),
('Esse aqui é o'),
('Baixou o preço do x de rico'),
('Olha como é fácil usar com x'),
('Esse aqui eu sou o primeiro a comprar'),
('Todo mundo pensa que eu gastei mais de x só que na verdade eu comprei por Y'),
('Vai fazer x tem que ter uma dessa aqui'),
('Acabei de x e é esse aqui eu eu uso'),
('Comprei o x mais procurado do tiktok'),
('Olha o que acabou de chegar'),
('Esse é o segredo de x sem fazer Y'),
('Agora acertei na compra'),
('Essa eu gostei tanto que comprei 2'),
('Eu não faço x sem isso aqui mais não'),
('Esse aqui é lançamento'),
('Ui, olha que capricho'),
('Essa aqui não precisa x não'),
('X, eu não saio de carro sem isso aqui mais não'),
('Essa aqui tem x (alguma característica exclusivo)'),
('Mais um pouquinho e o TikTok vai te dar de tão barato'),
('Menos de x com essa qualidade está dado'),
('Quer subir de nível em x?'),
('Agora eu quero ver x'),
('Acredite se quiser ele é x'),
('Essa daqui é raridade'),
('Essa aqui é padrão loja x (top)'),
('Só vai x agora se você quiser')
) AS v(texto)
ON CONFLICT DO NOTHING;